version: "3.9"

services:
  # Postgres
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Django web
  web:
    image: flowpal:latest
    container_name: flowpal_server
    command: gunicorn flowpal_project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=${POSTGRES_DB}
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0

  # Celery worker
  worker:
    image: flowpal:latest
    container_name: flowpal_celery
    command: celery -A flowpal_project worker -l info
    depends_on:
      - web
      - redis
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=${POSTGRES_DB}
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0

  # Celery Beat
  beat:
    image: flowpal:latest
    container_name: flowpal_celery_beat
    command: celery -A flowpal_project beat -l info
    depends_on:
      - web
      - redis
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=${POSTGRES_DB}
      - DJANGO_DB_USER=${POSTGRES_USER}
      - DJANGO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
